### ISSUE TITLE
UB: creation of uninitialized array of u8

### ISSUE THREAD

**Issue by saethlin** [rusticata/rusticata-macros#5]
This code executes UB: https://github.com/rusticata/rusticata-macros/blob/d0e0ab4cb4e060c37bfcbb0c2eebe1325186cad6/src/macros.rs#L157-L159

This code was added as a replacement for `mem::uninitialized` in https://github.com/rusticata/rusticata-macros/commit/b66c6ed01b592d1545ddc5aadee42aac4c13eb4e, but it fails to address the reason that `mem::uninitialized` was deprecated. This code is just as UB as calling `mem::uninitialized`. See the docs for `mem::uninitialized`: https://doc.rust-lang.org/stable/core/mem/fn.uninitialized.html

**Comment by chifflier** [comment]
Hi,

Thanks for the report. First of all, this function was only added as a "it may serve later" function, and is not used anywhere in rusticata's parsers so there is no immediate urgency nor directly impacted crate. Of course, if there is an UB it is important to fix as quickly as possible.

If I understand correctly, the proper fix is to use `write` (or similar) functions *before* calling `assume_init`? If so, I will release a new version quickly.

**Comment by chifflier** [comment]
As the macro was not used anywhere, and should have been rewritten to use `try_from` anyway (and as a function, not a macro), I decided to remove it.
